name = "LGT"
version = "0.1.0"
keywords = ["math", "gauge-theory", "lattice"]
defaultTargets = ["LGT"]

[leanOptions]
autoImplicit = false

[[require]]
name = "GaussianField"
git = "https://github.com/mrdouglasny/gaussian-field.git"
rev = "d1718af95a004fccf05caa439c344e7f42226e6e"

[[require]]
name = "MarkovSemigroups"
git = "https://github.com/mrdouglasny/markov-semigroups.git"
rev = "ad74f7e62fad35fe8db8e94ab00bc604e7fdb663"

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#v4.29.0"

[[lean_lib]]
name = "LGT"
